# *- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from schedulinist_main import Schedulinist


name_placeholder = 'i.e. "ארתור"'
availabilities_placeholder = 'dates where a linist can work. i.e. "5, 9, 12, 27" if the linist can work on the 5th, 9th, 12th and 27th of that month'
phone_placeholder = 'i.e. "050-123-4567"'
days_to_remove_placeholder = 'i.e. "2, 9"'
file_name_placeholder = 'i.e. "schedule" or "C:\\Users\\User\\Desktop\\schedule"'

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(854, 863)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(480, 590, 361, 221))
        self.calendarWidget.setAutoFillBackground(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.raw_availabilities_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.raw_availabilities_groupBox.setGeometry(QtCore.QRect(10, 10, 451, 801))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.raw_availabilities_groupBox.setFont(font)
        self.raw_availabilities_groupBox.setObjectName("raw_availabilities_groupBox")
        self.first_linist_name_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.first_linist_name_lineEdit.setGeometry(QtCore.QRect(80, 60, 121, 20))
        self.first_linist_name_lineEdit.setObjectName("first_linist_name_lineEdit")
        self.first_linist_availabilities_plainTextEdit = QtWidgets.QPlainTextEdit(self.raw_availabilities_groupBox)
        self.first_linist_availabilities_plainTextEdit.setGeometry(QtCore.QRect(40, 110, 161, 71))
        self.first_linist_availabilities_plainTextEdit.setObjectName("first_linist_availabilities_plainTextEdit")
        self.label = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 90, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_4.setGeometry(QtCore.QRect(40, 200, 71, 16))
        self.label_4.setObjectName("label_4")
        self.first_linist_phone_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.first_linist_phone_lineEdit.setGeometry(QtCore.QRect(80, 200, 121, 20))
        self.first_linist_phone_lineEdit.setObjectName("first_linist_phone_lineEdit_2")
        self.second_linist_phone_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.second_linist_phone_lineEdit.setGeometry(QtCore.QRect(80, 390, 121, 20))
        self.second_linist_phone_lineEdit.setObjectName("second_linist_phone_lineEdit")
        self.label_5 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_5.setGeometry(QtCore.QRect(40, 250, 47, 13))
        self.label_5.setObjectName("label_5")
        self.second_linist_availabilities_plainTextEdit = QtWidgets.QPlainTextEdit(self.raw_availabilities_groupBox)
        self.second_linist_availabilities_plainTextEdit.setGeometry(QtCore.QRect(40, 300, 161, 71))
        self.second_linist_availabilities_plainTextEdit.setObjectName("second_linist_availabilities_plainTextEdit")
        self.label_6 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 230, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_7.setGeometry(QtCore.QRect(40, 280, 71, 16))
        self.label_7.setObjectName("label_7")
        self.second_linist_name_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.second_linist_name_lineEdit.setGeometry(QtCore.QRect(80, 250, 121, 20))
        self.second_linist_name_lineEdit.setObjectName("second_linist_name_lineEdit")
        self.label_8 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_8.setGeometry(QtCore.QRect(40, 390, 71, 16))
        self.label_8.setObjectName("label_8")
        self.third_linist_availabilities_plainTextEdit = QtWidgets.QPlainTextEdit(self.raw_availabilities_groupBox)
        self.third_linist_availabilities_plainTextEdit.setGeometry(QtCore.QRect(40, 490, 161, 71))
        self.third_linist_availabilities_plainTextEdit.setObjectName("third_linist_availabilities_plainTextEdit")
        self.label_9 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_9.setGeometry(QtCore.QRect(40, 440, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_10.setGeometry(QtCore.QRect(40, 580, 71, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_11.setGeometry(QtCore.QRect(40, 470, 71, 16))
        self.label_11.setObjectName("label_11")
        self.third_linist_phone_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.third_linist_phone_lineEdit.setGeometry(QtCore.QRect(80, 580, 121, 20))
        self.third_linist_phone_lineEdit.setObjectName("third_linist_phone_lineEdit")
        self.label_12 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_12.setGeometry(QtCore.QRect(20, 420, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.third_linist_name_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.third_linist_name_lineEdit.setGeometry(QtCore.QRect(80, 440, 121, 20))
        self.third_linist_name_lineEdit.setObjectName("third_linist_name_lineEdit")
        self.label_13 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_13.setGeometry(QtCore.QRect(40, 630, 47, 13))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_14.setGeometry(QtCore.QRect(40, 770, 71, 16))
        self.label_14.setObjectName("label_14")
        self.fourth_linist_name_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.fourth_linist_name_lineEdit.setGeometry(QtCore.QRect(80, 630, 121, 20))
        self.fourth_linist_name_lineEdit.setObjectName("fourth_linist_name_lineEdit")
        self.label_15 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_15.setGeometry(QtCore.QRect(40, 660, 71, 16))
        self.label_15.setObjectName("label_15")
        self.fourth_linist_availabilities_plainTextEdit = QtWidgets.QPlainTextEdit(self.raw_availabilities_groupBox)
        self.fourth_linist_availabilities_plainTextEdit.setGeometry(QtCore.QRect(40, 680, 161, 71))
        self.fourth_linist_availabilities_plainTextEdit.setObjectName("fourth_linist_availabilities_plainTextEdit")
        self.label_16 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_16.setGeometry(QtCore.QRect(20, 610, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.fourth_linist_phone_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.fourth_linist_phone_lineEdit.setGeometry(QtCore.QRect(80, 770, 121, 20))
        self.fourth_linist_phone_lineEdit.setObjectName("fourth_linist_phone_lineEdit")
        self.label_17 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_17.setGeometry(QtCore.QRect(260, 60, 47, 13))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_18.setGeometry(QtCore.QRect(260, 200, 71, 16))
        self.label_18.setObjectName("label_18")
        self.fifth_linist_name_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.fifth_linist_name_lineEdit.setGeometry(QtCore.QRect(300, 60, 121, 20))
        self.fifth_linist_name_lineEdit.setObjectName("fifth_linist_name_lineEdit")
        self.label_19 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_19.setGeometry(QtCore.QRect(240, 40, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.fifth_linist_availabilities_plainTextEdit = QtWidgets.QPlainTextEdit(self.raw_availabilities_groupBox)
        self.fifth_linist_availabilities_plainTextEdit.setGeometry(QtCore.QRect(260, 110, 161, 71))
        self.fifth_linist_availabilities_plainTextEdit.setObjectName("fifth_linist_availabilities_plainTextEdit")
        self.fifth_linist_phone_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.fifth_linist_phone_lineEdit.setGeometry(QtCore.QRect(300, 200, 121, 20))
        self.fifth_linist_phone_lineEdit.setObjectName("fifth_linist_phone_lineEdit")
        self.label_20 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_20.setGeometry(QtCore.QRect(260, 90, 71, 16))
        self.label_20.setObjectName("label_20")
        self.sixth_linist_availabilities_plainTextEdit = QtWidgets.QPlainTextEdit(self.raw_availabilities_groupBox)
        self.sixth_linist_availabilities_plainTextEdit.setGeometry(QtCore.QRect(260, 300, 161, 71))
        self.sixth_linist_availabilities_plainTextEdit.setObjectName("sixth_linist_availabilities_plainTextEdit")
        self.label_21 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_21.setGeometry(QtCore.QRect(260, 280, 71, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_22.setGeometry(QtCore.QRect(260, 250, 47, 13))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_23.setGeometry(QtCore.QRect(260, 390, 71, 16))
        self.label_23.setObjectName("label_23")
        self.sixth_linist_name_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.sixth_linist_name_lineEdit.setGeometry(QtCore.QRect(300, 250, 121, 20))
        self.sixth_linist_name_lineEdit.setObjectName("sixth_linist_name_lineEdit")
        self.label_24 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_24.setGeometry(QtCore.QRect(240, 230, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.sixth_linist_phone_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.sixth_linist_phone_lineEdit.setGeometry(QtCore.QRect(300, 390, 121, 20))
        self.sixth_linist_phone_lineEdit.setObjectName("sixth_linist_phone_lineEdit")
        self.label_25 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_25.setGeometry(QtCore.QRect(260, 440, 47, 13))
        self.label_25.setObjectName("label_25")
        self.seventh_linist_phone_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.seventh_linist_phone_lineEdit.setGeometry(QtCore.QRect(300, 580, 121, 20))
        self.seventh_linist_phone_lineEdit.setObjectName("seventh_linist_phone_lineEdit")
        self.label_26 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_26.setGeometry(QtCore.QRect(260, 580, 71, 16))
        self.label_26.setObjectName("label_26")
        self.seventh_linist_name_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.seventh_linist_name_lineEdit.setGeometry(QtCore.QRect(300, 440, 121, 20))
        self.seventh_linist_name_lineEdit.setObjectName("seventh_linist_name_lineEdit")
        self.label_27 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_27.setGeometry(QtCore.QRect(260, 470, 71, 16))
        self.label_27.setObjectName("label_27")
        self.seventh_linist_availabilities_plainTextEdit = QtWidgets.QPlainTextEdit(self.raw_availabilities_groupBox)
        self.seventh_linist_availabilities_plainTextEdit.setGeometry(QtCore.QRect(260, 490, 161, 71))
        self.seventh_linist_availabilities_plainTextEdit.setObjectName("seventh_linist_availabilities_plainTextEdit")
        self.label_28 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_28.setGeometry(QtCore.QRect(240, 420, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.eighth_linist_name_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.eighth_linist_name_lineEdit.setGeometry(QtCore.QRect(300, 630, 121, 20))
        self.eighth_linist_name_lineEdit.setObjectName("eighth_linist_name_lineEdit")
        self.label_29 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_29.setGeometry(QtCore.QRect(260, 630, 47, 13))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_30.setGeometry(QtCore.QRect(260, 660, 71, 16))
        self.label_30.setObjectName("label_30")
        self.eighth_linist_phone_lineEdit = QtWidgets.QLineEdit(self.raw_availabilities_groupBox)
        self.eighth_linist_phone_lineEdit.setGeometry(QtCore.QRect(300, 770, 121, 20))
        self.eighth_linist_phone_lineEdit.setObjectName("eighth_linist_phone_lineEdit")
        self.eighth_linist_availabilities_plainTextEdit = QtWidgets.QPlainTextEdit(self.raw_availabilities_groupBox)
        self.eighth_linist_availabilities_plainTextEdit.setGeometry(QtCore.QRect(260, 680, 161, 71))
        self.eighth_linist_availabilities_plainTextEdit.setObjectName("eighth_linist_availabilities_plainTextEdit")
        self.label_31 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_31.setGeometry(QtCore.QRect(260, 770, 71, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.raw_availabilities_groupBox)
        self.label_32.setGeometry(QtCore.QRect(240, 610, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.days_to_remove_exp_path_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.days_to_remove_exp_path_groupBox.setGeometry(QtCore.QRect(480, 10, 361, 191))
        self.days_to_remove_exp_path_groupBox.setObjectName("days_to_remove_exp_path_groupBox")
        self.label_33 = QtWidgets.QLabel(self.days_to_remove_exp_path_groupBox)
        self.label_33.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_33.setObjectName("label_33")
        self.days_to_remove_lineEdit = QtWidgets.QLineEdit(self.days_to_remove_exp_path_groupBox)
        self.days_to_remove_lineEdit.setGeometry(QtCore.QRect(110, 20, 231, 20))
        self.days_to_remove_lineEdit.setObjectName("days_to_remove_lineEdit")
        self.label_34 = QtWidgets.QLabel(self.days_to_remove_exp_path_groupBox)
        self.label_34.setGeometry(QtCore.QRect(20, 60, 81, 16))
        self.label_34.setObjectName("label_34")
        self.file_name_lineEdit = QtWidgets.QLineEdit(self.days_to_remove_exp_path_groupBox)
        self.file_name_lineEdit.setGeometry(QtCore.QRect(110, 60, 231, 20))
        self.file_name_lineEdit.setObjectName("file_name_lineEdit")
        self.export_pushButton = QtWidgets.QPushButton(self.days_to_remove_exp_path_groupBox)
        self.export_pushButton.setGeometry(QtCore.QRect(250, 140, 91, 31))
        self.export_pushButton.setObjectName("export_pushButton")
        self.or_phones_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.or_phones_groupBox.setGeometry(QtCore.QRect(480, 470, 361, 101))
        self.or_phones_groupBox.setObjectName("or_phones_groupBox")
        self.label_35 = QtWidgets.QLabel(self.or_phones_groupBox)
        self.label_35.setGeometry(QtCore.QRect(260, 20, 81, 16))
        self.label_35.setObjectName("label_35")
        self.ward_phone_lineEdit = QtWidgets.QLineEdit(self.or_phones_groupBox)
        self.ward_phone_lineEdit.setGeometry(QtCore.QRect(20, 20, 231, 20))
        self.ward_phone_lineEdit.setObjectName("ward_phone_lineEdit")
        self.label_36 = QtWidgets.QLabel(self.or_phones_groupBox)
        self.label_36.setGeometry(QtCore.QRect(260, 70, 81, 16))
        self.label_36.setObjectName("label_36")
        self.cath_lab_phone_lineEdit = QtWidgets.QLineEdit(self.or_phones_groupBox)
        self.cath_lab_phone_lineEdit.setGeometry(QtCore.QRect(20, 70, 231, 20))
        self.cath_lab_phone_lineEdit.setObjectName("cath_lab_phone_lineEdit")
        self.misc_options_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.misc_options_groupBox.setGeometry(QtCore.QRect(480, 210, 361, 251))
        self.misc_options_groupBox.setObjectName("misc_options_groupBox")
        self.label_37 = QtWidgets.QLabel(self.misc_options_groupBox)
        self.label_37.setGeometry(QtCore.QRect(40, 60, 21, 16))
        self.label_37.setObjectName("label_37")
        self.multiple_export_count_comboBox = QtWidgets.QComboBox(self.misc_options_groupBox)
        self.multiple_export_count_comboBox.setGeometry(QtCore.QRect(70, 60, 41, 22))
        self.multiple_export_count_comboBox.setObjectName("multiple_export_count_comboBox")
        self.multiple_export_count_comboBox.addItem("")
        self.multiple_export_count_comboBox.addItem("")
        self.multiple_export_count_comboBox.addItem("")
        self.multiple_export_count_comboBox.addItem("")
        self.multiple_export_count_comboBox.addItem("")
        self.multiple_export_count_comboBox.addItem("")
        self.multiple_export_count_comboBox.addItem("")
        self.multiple_export_count_comboBox.addItem("")
        self.multiple_export_count_comboBox.addItem("")
        self.label_38 = QtWidgets.QLabel(self.misc_options_groupBox)
        self.label_38.setGeometry(QtCore.QRect(120, 60, 161, 16))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.misc_options_groupBox)
        self.label_39.setGeometry(QtCore.QRect(40, 80, 161, 16))
        self.label_39.setObjectName("label_39")
        self.colorful_export_checkBox = QtWidgets.QCheckBox(self.misc_options_groupBox)
        self.colorful_export_checkBox.setGeometry(QtCore.QRect(20, 30, 241, 17))
        self.colorful_export_checkBox.setObjectName("colorful_export_checkBox")
        self.multiple_export_checkBox = QtWidgets.QCheckBox(self.misc_options_groupBox)
        self.multiple_export_checkBox.setGeometry(QtCore.QRect(20, 60, 16, 17))
        self.multiple_export_checkBox.setText("")
        self.multiple_export_checkBox.setObjectName("multiple_export_checkBox")
        self.dial = QtWidgets.QDial(self.misc_options_groupBox)
        self.dial.setGeometry(QtCore.QRect(280, 160, 50, 64))
        self.dial.setObjectName("dial")
        self.hidden_pic = QtWidgets.QLabel(self.centralwidget)
        self.hidden_pic.setGeometry(QtCore.QRect(860, 20, 661, 391))
        self.hidden_pic.setText("")
        self.hidden_pic.setPixmap(QtGui.QPixmap("schedulinist_assets/kerner.JPG"))
        self.hidden_pic.setScaledContents(True)
        self.hidden_pic.setObjectName("hidden_pic")
        self.baloons_pic = QtWidgets.QLabel(self.centralwidget)
        self.baloons_pic.setGeometry(QtCore.QRect(860, 430, 661, 381))
        self.baloons_pic.setText("")
        self.baloons_pic.setPixmap(QtGui.QPixmap("schedulinist_assets/baloons.JPG"))
        self.baloons_pic.setScaledContents(True)
        self.baloons_pic.setObjectName("baloons_pic")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 854, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport_file_with_current_values = QtWidgets.QAction(MainWindow)
        self.actionExport_file_with_current_values.setObjectName("actionExport_file_with_current_values")
        self.menuFile.addAction(self.actionExport_file_with_current_values)
        self.menuFile.addAction(self.actionExport_file_with_current_values)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDefaults_all_values = QtWidgets.QAction(MainWindow)
        self.actionDefaults_all_values.setObjectName("actionDefaults_all_values")
        self.menuFile.addAction(self.actionDefaults_all_values)
        self.actionClear_all_values = QtWidgets.QAction(MainWindow)
        self.actionClear_all_values.setObjectName("actionClear_all_values")
        self.menuFile.addAction(self.actionClear_all_values)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Menu bar actions:
        self.export_pushButton.clicked.connect(self.export_file)
        self.actionExport_file_with_current_values.triggered.connect(self.export_file)
        self.actionDefaults_all_values.triggered.connect(self.default_all_values)
        self.actionClear_all_values.triggered.connect(self.clear_all_values)
        self.actionAbout.triggered.connect(lambda: self.to_be_added("About"))
        self.actionDocumentation.triggered.connect(lambda: self.to_be_added("Documentation"))
        
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Schedulinist v1.0.0"))
        self.raw_availabilities_groupBox.setTitle(_translate("MainWindow", "Availabilities"))
        self.label.setText(_translate("MainWindow", "1."))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.label_3.setText(_translate("MainWindow", "Availabilities:"))
        self.label_4.setText(_translate("MainWindow", "Phone:"))
        self.label_5.setText(_translate("MainWindow", "Name:"))
        self.label_6.setText(_translate("MainWindow", "2."))
        self.label_7.setText(_translate("MainWindow", "Availabilities:"))
        self.label_8.setText(_translate("MainWindow", "Phone:"))
        self.label_9.setText(_translate("MainWindow", "Name:"))
        self.label_10.setText(_translate("MainWindow", "Phone:"))
        self.label_11.setText(_translate("MainWindow", "Availabilities:"))
        self.label_12.setText(_translate("MainWindow", "3."))
        self.label_13.setText(_translate("MainWindow", "Name:"))
        self.label_14.setText(_translate("MainWindow", "Phone:"))
        self.label_15.setText(_translate("MainWindow", "Availabilities:"))
        self.label_16.setText(_translate("MainWindow", "4."))
        self.label_17.setText(_translate("MainWindow", "Name:"))
        self.label_18.setText(_translate("MainWindow", "Phone:"))
        self.label_19.setText(_translate("MainWindow", "5."))
        self.label_20.setText(_translate("MainWindow", "Availabilities:"))
        self.label_21.setText(_translate("MainWindow", "Availabilities:"))
        self.label_22.setText(_translate("MainWindow", "Name:"))
        self.label_23.setText(_translate("MainWindow", "Phone:"))
        self.label_24.setText(_translate("MainWindow", "6."))
        self.label_25.setText(_translate("MainWindow", "Name:"))
        self.label_26.setText(_translate("MainWindow", "Phone:"))
        self.label_27.setText(_translate("MainWindow", "Availabilities:"))
        self.label_28.setText(_translate("MainWindow", "7."))
        self.label_29.setText(_translate("MainWindow", "Name:"))
        self.label_30.setText(_translate("MainWindow", "Availabilities:"))
        self.label_31.setText(_translate("MainWindow", "Phone:"))
        self.label_32.setText(_translate("MainWindow", "8."))
        self.days_to_remove_exp_path_groupBox.setTitle(_translate("MainWindow", "Export"))
        self.label_33.setText(_translate("MainWindow", "Days to remove:"))
        self.label_34.setText(_translate("MainWindow", "File Name:"))
        self.export_pushButton.setText(_translate("MainWindow", "Export"))
        self.or_phones_groupBox.setTitle(_translate("MainWindow", "General phone numbers"))
        self.label_35.setText(_translate("MainWindow", "מחלקה"))
        self.label_36.setText(_translate("MainWindow", "חדר צנתורים"))
        self.misc_options_groupBox.setTitle(_translate("MainWindow", "Misc. options"))
        self.label_37.setText(_translate("MainWindow", "Run"))
        self.multiple_export_count_comboBox.setItemText(0, _translate("MainWindow", "2"))
        self.multiple_export_count_comboBox.setItemText(1, _translate("MainWindow", "3"))
        self.multiple_export_count_comboBox.setItemText(2, _translate("MainWindow", "4"))
        self.multiple_export_count_comboBox.setItemText(3, _translate("MainWindow", "5"))
        self.multiple_export_count_comboBox.setItemText(4, _translate("MainWindow", "6"))
        self.multiple_export_count_comboBox.setItemText(5, _translate("MainWindow", "7"))
        self.multiple_export_count_comboBox.setItemText(6, _translate("MainWindow", "8"))
        self.multiple_export_count_comboBox.setItemText(7, _translate("MainWindow", "9"))
        self.multiple_export_count_comboBox.setItemText(8, _translate("MainWindow", "10"))
        self.label_38.setText(_translate("MainWindow", "times and save each run on "))
        self.label_39.setText(_translate("MainWindow", "different Excel sheet."))
        self.colorful_export_checkBox.setText(_translate("MainWindow", "Each linist days in a different color."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExport_file_with_current_values.setText(_translate("MainWindow", "Export file with current values"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionDefaults_all_values.setText(_translate("MainWindow", "Default all values"))
        self.actionClear_all_values.setText(_translate("MainWindow", "Clear all values"))
        # default values:
        self.first_linist_name_lineEdit.setPlaceholderText(name_placeholder)
        self.first_linist_name_lineEdit.setText("לירן")
        self.first_linist_availabilities_plainTextEdit.setPlaceholderText(availabilities_placeholder)
        self.first_linist_phone_lineEdit.setPlaceholderText(phone_placeholder)
        self.first_linist_phone_lineEdit.setText("censored phone number")

        self.second_linist_name_lineEdit.setPlaceholderText(name_placeholder)
        self.second_linist_name_lineEdit.setText("אשר")
        self.second_linist_availabilities_plainTextEdit.setPlaceholderText(availabilities_placeholder)
        self.second_linist_phone_lineEdit.setPlaceholderText(phone_placeholder)
        self.second_linist_phone_lineEdit.setText("censored phone number")

        self.third_linist_name_lineEdit.setPlaceholderText(name_placeholder)
        self.third_linist_name_lineEdit.setText("ינאי")
        self.third_linist_availabilities_plainTextEdit.setPlaceholderText(availabilities_placeholder)
        self.third_linist_phone_lineEdit.setPlaceholderText(phone_placeholder)
        self.third_linist_phone_lineEdit.setText("censored phone number")

        self.fourth_linist_name_lineEdit.setPlaceholderText(name_placeholder)
        self.fourth_linist_name_lineEdit.setText("עמית")
        self.fourth_linist_availabilities_plainTextEdit.setPlaceholderText(availabilities_placeholder)
        self.fourth_linist_phone_lineEdit.setPlaceholderText(phone_placeholder)
        self.fourth_linist_phone_lineEdit.setText("censored phone number")

        self.fifth_linist_name_lineEdit.setPlaceholderText(name_placeholder)
        self.fifth_linist_name_lineEdit.setText("יוני")
        self.fifth_linist_availabilities_plainTextEdit.setPlaceholderText(availabilities_placeholder)
        self.fifth_linist_phone_lineEdit.setPlaceholderText(phone_placeholder)
        self.fifth_linist_phone_lineEdit.setText("censored phone number")

        self.sixth_linist_name_lineEdit.setPlaceholderText(name_placeholder)
        self.sixth_linist_name_lineEdit.setText("מריה")
        self.sixth_linist_availabilities_plainTextEdit.setPlaceholderText(availabilities_placeholder)
        self.sixth_linist_phone_lineEdit.setPlaceholderText(phone_placeholder)
        self.sixth_linist_phone_lineEdit.setText("censored phone number")

        self.seventh_linist_name_lineEdit.setPlaceholderText(name_placeholder)
        self.seventh_linist_availabilities_plainTextEdit.setPlaceholderText(availabilities_placeholder)
        self.seventh_linist_phone_lineEdit.setPlaceholderText(phone_placeholder)


        self.eighth_linist_name_lineEdit.setPlaceholderText(name_placeholder)
        self.eighth_linist_availabilities_plainTextEdit.setPlaceholderText(availabilities_placeholder)
        self.eighth_linist_phone_lineEdit.setPlaceholderText(phone_placeholder)

        self.days_to_remove_lineEdit.setPlaceholderText(days_to_remove_placeholder)
        self.file_name_lineEdit.setPlaceholderText(file_name_placeholder)
        self.ward_phone_lineEdit.setPlaceholderText(phone_placeholder)
        self.ward_phone_lineEdit.setText("censored phone number")
        self.cath_lab_phone_lineEdit.setPlaceholderText(phone_placeholder)
        self.cath_lab_phone_lineEdit.setText("censored phone number")


    def clear_all_values(self):
        self.first_linist_name_lineEdit.setText("")
        self.first_linist_phone_lineEdit.setText("")
        self.second_linist_name_lineEdit.setText("")
        self.second_linist_phone_lineEdit.setText("")
        self.third_linist_name_lineEdit.setText("")
        self.third_linist_phone_lineEdit.setText("")
        self.fourth_linist_name_lineEdit.setText("")
        self.fourth_linist_phone_lineEdit.setText("")
        self.fifth_linist_name_lineEdit.setText("")
        self.fifth_linist_phone_lineEdit.setText("")
        self.sixth_linist_name_lineEdit.setText("")
        self.sixth_linist_phone_lineEdit.setText("")
        self.seventh_linist_name_lineEdit.setText("")
        self.seventh_linist_phone_lineEdit.setText("")
        self.eighth_linist_name_lineEdit.setText("")
        self.eighth_linist_phone_lineEdit.setText("")

        self.first_linist_availabilities_plainTextEdit.setPlainText("")
        self.second_linist_availabilities_plainTextEdit.setPlainText("")
        self.third_linist_availabilities_plainTextEdit.setPlainText("")
        self.fourth_linist_availabilities_plainTextEdit.setPlainText("")
        self.fifth_linist_availabilities_plainTextEdit.setPlainText("")
        self.sixth_linist_availabilities_plainTextEdit.setPlainText("")


    def default_all_values(self):
        self.clear_all_values()

        self.first_linist_name_lineEdit.setText("לירן")
        self.first_linist_availabilities_plainTextEdit.setPlainText("")
        self.first_linist_phone_lineEdit.setText("censored phone number")

        self.second_linist_name_lineEdit.setText("אשר")
        self.second_linist_availabilities_plainTextEdit.setPlainText("")
        self.second_linist_phone_lineEdit.setText("censored phone number")

      
        self.third_linist_name_lineEdit.setText("ינאי")
        self.third_linist_availabilities_plainTextEdit.setPlainText("")
        self.third_linist_phone_lineEdit.setText("censored phone number")

        self.fourth_linist_name_lineEdit.setText("עמית")
        self.fourth_linist_availabilities_plainTextEdit.setPlainText("")
        self.fourth_linist_phone_lineEdit.setText("censored phone number")

        self.fifth_linist_name_lineEdit.setText("יוני")
        self.fifth_linist_availabilities_plainTextEdit.setPlainText("")
        self.fifth_linist_phone_lineEdit.setText("censored phone number")

        
        self.sixth_linist_name_lineEdit.setText("מריה")
        self.sixth_linist_availabilities_plainTextEdit.setPlainText("")
        self.sixth_linist_phone_lineEdit.setText("censored phone number")

        self.ward_phone_lineEdit.setText("censored phone number")
        self.cath_lab_phone_lineEdit.setText("censored phone number")


    def input_error_popup(self, message):
        msg = QMessageBox()
        tmp_txt = "Something you inserted into \"" + message + "\" could not be processed."
        msg.setWindowTitle("Input error!")
        msg.setText(tmp_txt)
        msg.setInformativeText("Please retype the data and try again.")
        msg.setIcon(QMessageBox.Critical)
        x = msg.exec_()


    def undesirable_days_popup(self, unassigned_days_list):
        msg = QMessageBox()
        tmp_txt = "The following dates were unassigned: \n" + str(unassigned_days_list)
        msg.setWindowTitle("Unassigned days notice!")
        msg.setText(tmp_txt)
        msg.setInformativeText("A file was exported for you, however, you should find a linist willing to work on the above days and try again.")
        msg.setIcon(QMessageBox.Information)
        x = msg.exec_()


    def to_be_added(self, message):
        msg = QMessageBox()
        tmp_txt = "\"" + message + "\" will be added in the next Schedulinist version."
        msg.setWindowTitle("This feature has not yet been added!")
        msg.setText(tmp_txt)
        msg.setInformativeText("Sorry buddy, I still did not add this feature.")
        msg.setIcon(QMessageBox.Information)
        x = msg.exec_()


    def get_linist_data(self, linist_name, linist_phone, linist_avail, linist_window, exp_list):
        tmp_avail_dict = {}
        try:
            tmp_name = (linist_name.text()).replace(" ", "")
            tmp_availabilities = ((linist_avail.toPlainText()).replace(" ", ""))
            tmp_phone = str((linist_phone.text()).replace(" ", ""))
            if tmp_name != "":
                if tmp_availabilities == "":
                    tmp_avail_dict = {"name": tmp_name, "availabilities": [], "phone": tmp_phone}
                    exp_list.append(tmp_avail_dict)
                else:
                    tmp_availabilities = tmp_availabilities.split(",")
                    tmp_availabilities = list(filter(None, tmp_availabilities))
                    tmp_avail_dict = {"name": tmp_name, "availabilities": [int(i) for i in tmp_availabilities], "phone": tmp_phone}
                    exp_list.append(tmp_avail_dict)
        except:
            self.input_error_popup(linist_window)
            

    # def get_days_to_remove(self, )


    def export_file(self):
        exp_raw_availabilities = []
        tmp_avail_dict = {}
        exp_days_to_remove = []
        exp_path = None
        exp_month_year = []
        exp_or_phones = [
    {"name": "מחלקה", "phone": "censored phone number"},
    {"name": "חדר צנתורים", "phone": "censored phone number"},
]
        # Get 8 linist data:
        self.get_linist_data(self.first_linist_name_lineEdit, self.first_linist_phone_lineEdit, self.first_linist_availabilities_plainTextEdit, "first linist window", exp_raw_availabilities)
        self.get_linist_data(self.second_linist_name_lineEdit, self.second_linist_phone_lineEdit, self.second_linist_availabilities_plainTextEdit, "second linist window", exp_raw_availabilities)
        self.get_linist_data(self.third_linist_name_lineEdit, self.third_linist_phone_lineEdit, self.third_linist_availabilities_plainTextEdit, "third linist window", exp_raw_availabilities)
        self.get_linist_data(self.fourth_linist_name_lineEdit, self.fourth_linist_phone_lineEdit, self.fourth_linist_availabilities_plainTextEdit, "fourth linist window", exp_raw_availabilities)
        self.get_linist_data(self.fifth_linist_name_lineEdit, self.fifth_linist_phone_lineEdit, self.fifth_linist_availabilities_plainTextEdit, "fifth linist window", exp_raw_availabilities)
        self.get_linist_data(self.sixth_linist_name_lineEdit, self.sixth_linist_phone_lineEdit, self.sixth_linist_availabilities_plainTextEdit, "sixth linist window", exp_raw_availabilities)
        self.get_linist_data(self.seventh_linist_name_lineEdit, self.seventh_linist_phone_lineEdit, self.seventh_linist_availabilities_plainTextEdit, "seventh linist window", exp_raw_availabilities)
        self.get_linist_data(self.eighth_linist_name_lineEdit, self.eighth_linist_phone_lineEdit, self.eighth_linist_availabilities_plainTextEdit, "eighth linist window", exp_raw_availabilities)
        # TODO: add error handling and other windows
        # TODO: cache data and other funcs
        # Get days to remove:
        try:
            tmp_days_to_remove = ((self.days_to_remove_lineEdit.text()).replace(" ", ""))
            if tmp_days_to_remove == "":
                tmp_days_to_remove = []
            else:
                tmp_days_to_remove = tmp_days_to_remove.split(",")
                tmp_days_to_remove = list(filter(None, tmp_days_to_remove))
                exp_days_to_remove = list(set([int(i) for i in tmp_days_to_remove]))
            # print("days to remove" , exp_days_to_remove)
        except:
            self.input_error_popup("days to remove window")
        # Get export_path:
        try:
            tmp_txt = (self.file_name_lineEdit.text()).replace(" ", "")
            if tmp_txt == "":
                exp_path = None
            else:
                tmp_exp_path = tmp_txt
                exp_path = tmp_exp_path
        except:
            self.input_error_popup("File Name window")
        # Get month year:
        try:
            tmp_month = (self.calendarWidget.selectedDate()).month()
            tmp_year = (self.calendarWidget.selectedDate()).year()
            exp_month_year = [tmp_month, tmp_year]
        except:
            self.input_error_popup("calendar window")
        # Get OR phone numbers:
        try:
            tmp_department_phone = (self.ward_phone_lineEdit.text()).replace(" ", "")
            tmp_cath_lab_phone = (self.cath_lab_phone_lineEdit.text()).replace(" ", "")
            if tmp_department_phone != "":
                exp_or_phones[0]["phone"] = tmp_department_phone
            if tmp_cath_lab_phone != "":
                exp_or_phones[1]["phone"] = tmp_cath_lab_phone
        except:
            self.input_error_message("General phone numbers window")
        # Instantiate a Schedulinist object:
        try:
            
            tmp_scheduler = Schedulinist(exp_month_year, exp_days_to_remove, exp_raw_availabilities, exp_path, exp_or_phones)
            tmp_undesirable = tmp_scheduler.undesirable_days()
            if not tmp_undesirable:
                tmp_scheduler.export_excel()
            else:
                self.undesirable_days_popup(tmp_undesirable)
                tmp_scheduler.export_excel()
        except:
            self.input_error_popup("UNKNOWN")        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.setWindowIcon(QtGui.QIcon("schedulinist_assets/schedu_icon.png"))
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

# TODO: add documentation and about
# TODO: start calendar widget from next month.
# TODO: add function features (and browse)
# TODO: write to excel number of times each linist was assigned
# TODO: add caching of values
# TODO: upon exporting, try open a file if exists, if it does add to it a new worksheet instead of 
#       rewriting it completely to allow appending to same file always.
